import datetime

data_good = [{'name_post': '[READY] Thank Optimism - powered by ThriveCoin',
              'link': 'https://gov.optimism.io/t/ready-thank-optimism-powered-by-thrivecoin/6104', 'views_post': '724',
              'date_post': datetime.datetime(2023, 6, 25, 8, 25, 10, 447000)}, {
                 'name_post': '[DRAFT] Web3xplorer - A curated web platform to discover useful web3 apps, resources and tools',
                 'link': 'https://gov.optimism.io/t/draft-web3xplorer-a-curated-web-platform-to-discover-useful-web3-apps-resources-and-tools/6143',
                 'views_post': '145', 'date_post': datetime.datetime(2023, 6, 25, 7, 58, 13, 203000)},
             {'name_post': 'Superchain Governance Deep Dive',
              'link': 'https://gov.optimism.io/t/superchain-governance-deep-dive/5920', 'views_post': '839',
              'date_post': datetime.datetime(2023, 6, 25, 3, 20, 29, 883000)},
             {'name_post': '[READY] TechNERD program', 'link': 'https://gov.optimism.io/t/ready-technerd-program/6087',
              'views_post': '410', 'date_post': datetime.datetime(2023, 6, 25, 3, 15, 4, 844000)},
             {'name_post': '[DRAFT] OPdelegate.com', 'link': 'https://gov.optimism.io/t/draft-opdelegate-com/6176',
              'views_post': '257', 'date_post': datetime.datetime(2023, 6, 25, 3, 12, 34, 752000)},
             {'name_post': '[DRAFT] Velodrome: Spread Awareness Through Direct Outreach and Onboarding',
              'link': 'https://gov.optimism.io/t/draft-velodrome-spread-awareness-through-direct-outreach-and-onboarding/6180',
              'views_post': '200', 'date_post': datetime.datetime(2023, 6, 25, 3, 0, 55, 206000)},
             {'name_post': '[READY] ITU Blockchain - Spreading Optimistic Vision to the Local Blockchain Ecosystem',
              'link': 'https://gov.optimism.io/t/ready-itu-blockchain-spreading-optimistic-vision-to-the-local-blockchain-ecosystem/6197',
              'views_post': '173', 'date_post': datetime.datetime(2023, 6, 24, 23, 2, 42, 58000)},
             {'name_post': '[DRAFT] Enable aOP as A Votable Token in Optimism’s Governance',
              'link': 'https://gov.optimism.io/t/draft-enable-aop-as-a-votable-token-in-optimisms-governance/6199',
              'views_post': '155', 'date_post': datetime.datetime(2023, 6, 24, 20, 41, 34, 665000)},
             {'name_post': '[OUTLINE] Ethereum Signed Optimistic Vision',
              'link': 'https://gov.optimism.io/t/outline-ethereum-signed-optimistic-vision/6107', 'views_post': '269',
              'date_post': datetime.datetime(2023, 6, 24, 20, 12, 18, 376000)}, {
                 'name_post': '[DRAFT] Velodrome: Fostering Inclusive Governance through Leading Optimism Builders and Long-term Users',
                 'link': 'https://gov.optimism.io/t/draft-velodrome-fostering-inclusive-governance-through-leading-optimism-builders-and-long-term-users/6186',
                 'views_post': '269', 'date_post': datetime.datetime(2023, 6, 24, 17, 37, 12, 890000)},
             {'name_post': 'Clarification on OP Token Supply',
              'link': 'https://gov.optimism.io/t/clarification-on-op-token-supply/5589', 'views_post': '1.6k',
              'date_post': datetime.datetime(2023, 6, 24, 16, 32, 55, 198000)},
             {'name_post': 'Op Airdrop Rules', 'link': 'https://gov.optimism.io/t/op-airdrop-rules/5564',
              'views_post': '767', 'date_post': datetime.datetime(2023, 6, 24, 16, 28, 14, 214000)}, {
                 'name_post': '[Draft] The Optimists Thriving Guide (un)Conference: A Co-created week long event gathering voices from the ecosystem',
                 'link': 'https://gov.optimism.io/t/draft-the-optimists-thriving-guide-un-conference-a-co-created-week-long-event-gathering-voices-from-the-ecosystem/6192',
                 'views_post': '107', 'date_post': datetime.datetime(2023, 6, 24, 15, 49, 12, 775000)},
             {'name_post': '[DRAFT] Giveth: Unleashing the power of Impact DAOs',
              'link': 'https://gov.optimism.io/t/draft-giveth-unleashing-the-power-of-impact-daos/6178',
              'views_post': '128', 'date_post': datetime.datetime(2023, 6, 24, 14, 44, 56, 511000)}]
